// Single Vite config with two modes:
//   `vite build --mode library` → publishable ESM artifact in dist/.
//   `vite` / `vite build`       → demo dev server / demo bundle for GH Pages.
//
// The library build has no runtime dependencies (the component duck-types
// against an HlsIFramesOnly-shaped player). hls-video-element, media-chrome,
// and hls.js are runtime requirements of the consumer, not bundled here.

import { defineConfig } from 'vite';
import { copyFileSync, mkdirSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));

const libraryConfig = {
  build: {
    outDir: 'dist',
    emptyOutDir: true,
    sourcemap: true,
    minify: false,
    lib: {
      entry: resolve(__dirname, 'src/media-preview-hls-iframe.ts'),
      formats: ['es'],
      fileName: () => 'media-preview-hls-iframe.js',
    },
    rollupOptions: {
      external: [],
    },
  },
  plugins: [
    {
      // demo/lib/ is committed; this banner reminds anyone opening the built
      // file that the source lives in src/. Uses `generateBundle` (not
      // `renderChunk`) so the banner lands above esbuild's private-field
      // helpers, which Vite injects at the top of the chunk after Rollup's
      // renderChunk pass.
      name: 'built-file-banner',
      generateBundle(_, bundle) {
        for (const chunk of Object.values(bundle)) {
          if (chunk.type === 'chunk') {
            chunk.code = '/*! Generated by `npm run build` — do not edit. Source: src/media-preview-hls-iframe.ts */\n' + chunk.code;
          }
        }
      },
    },
    {
      // Mirror the built JS into demo/lib/ so the demo/ folder is fully
      // self-contained — its importmap and the advanced demo's Vite alias
      // both resolve here, and the folder can be deployed (or zipped up)
      // without dragging the rest of the repo along.
      name: 'mirror-to-demo-lib',
      closeBundle() {
        mkdirSync(resolve(__dirname, 'demo/lib'), { recursive: true });
        for (const f of ['media-preview-hls-iframe.js', 'media-preview-hls-iframe.js.map']) {
          copyFileSync(
            resolve(__dirname, 'dist', f),
            resolve(__dirname, 'demo/lib', f),
          );
        }
      },
    },
  ],
};

// Both demos resolve `media-preview-hls-iframe` to the same file the
// static index.html importmap points to. Run `npm run build` first so the
// alias target exists.
const demoConfig = {
  root: resolve(__dirname, 'demo'),
  base: process.env.VITE_BASE || '/',
  resolve: {
    alias: [
      {
        find: /^media-preview-hls-iframe$/,
        replacement: resolve(__dirname, 'demo/lib/media-preview-hls-iframe.js'),
      },
    ],
  },
  server: { port: 5173 },
  build: {
    outDir: resolve(__dirname, 'dist-demo'),
    emptyOutDir: true,
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'demo/index.html'),
        advanced: resolve(__dirname, 'demo/advanced.html'),
      },
    },
  },
};

export default defineConfig(({ mode }) =>
  mode === 'library' ? libraryConfig : demoConfig,
);
