// Single Vite config with two modes:
//   `vite build --mode library` → publishable ESM artifact in dist/.
//   `vite` / `vite build`       → demo dev server / demo bundle for GH Pages.
//
// The library build has no runtime dependencies (the component duck-types
// against an HlsIFramesOnly-shaped player). hls-video-element, media-chrome,
// and hls.js are runtime requirements of the consumer, not bundled here.

import { defineConfig } from 'vite';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));

const libraryConfig = {
  build: {
    outDir: 'dist',
    emptyOutDir: true,
    sourcemap: true,
    minify: false,
    lib: {
      entry: resolve(__dirname, 'src/media-preview-hls-iframe.ts'),
      formats: ['es'],
      fileName: () => 'media-preview-hls-iframe.js',
    },
    rollupOptions: {
      external: [],
    },
  },
  plugins: [
    {
      // Banner reminding anyone opening the built file that the source lives
      // in src/. Uses `generateBundle` (not `renderChunk`) so the banner
      // lands above esbuild's private-field helpers, which Vite injects at
      // the top of the chunk after Rollup's renderChunk pass.
      name: 'built-file-banner',
      generateBundle(_, bundle) {
        for (const chunk of Object.values(bundle)) {
          if (chunk.type === 'chunk') {
            chunk.code = '/*! Generated by `npm run build` — do not edit. Source: src/media-preview-hls-iframe.ts */\n' + chunk.code;
          }
        }
      },
    },
  ],
};

// The demo intentionally consumes the *published* package from jsDelivr
// (see the importmaps in demo/index.html and demo/advanced.html), so it
// reflects what consumers actually see. We mark `media-preview-hls-iframe`
// as external in both dev pre-bundle and build, which leaves the bare import
// untouched in the served/built scripts; the browser then resolves it via
// the importmap. Local-only changes to src/ won't appear in the demo until
// they're published — for in-progress component work, use the unit / e2e
// tests, not the demo.
const externalPackage = 'media-preview-hls-iframe';

const demoConfig = {
  root: resolve(__dirname, 'demo'),
  base: process.env.VITE_BASE || '/',
  optimizeDeps: {
    exclude: [externalPackage],
  },
  server: { port: 5173 },
  build: {
    outDir: resolve(__dirname, 'dist-demo'),
    emptyOutDir: true,
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'demo/index.html'),
        advanced: resolve(__dirname, 'demo/advanced.html'),
      },
      external: [externalPackage],
    },
  },
};

export default defineConfig(({ mode }) =>
  mode === 'library' ? libraryConfig : demoConfig,
);
