// Single Vite config with two modes:
//   `vite build --mode library` → publishable ESM artifact in dist/.
//   `vite` / `vite build`       → demo dev server / demo bundle for GH Pages.
//
// The library build has no runtime dependencies (the component duck-types
// against an HlsIFramesOnly-shaped player). hls-video-element, media-chrome,
// and hls.js are runtime requirements of the consumer, not bundled here.

import { defineConfig } from 'vite';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));

const libraryConfig = {
  build: {
    outDir: 'dist',
    emptyOutDir: true,
    sourcemap: true,
    minify: false,
    lib: {
      entry: resolve(__dirname, 'src/media-preview-hls-iframe.ts'),
      formats: ['es'],
      fileName: () => 'media-preview-hls-iframe.js',
    },
    rollupOptions: {
      external: [],
    },
  },
  plugins: [
    {
      // Banner reminding anyone opening the built file that the source lives
      // in src/. Uses `generateBundle` (not `renderChunk`) so the banner
      // lands above esbuild's private-field helpers, which Vite injects at
      // the top of the chunk after Rollup's renderChunk pass.
      name: 'built-file-banner',
      generateBundle(_, bundle) {
        for (const chunk of Object.values(bundle)) {
          if (chunk.type === 'chunk') {
            chunk.code = '/*! Generated by `npm run build` — do not edit. Source: src/media-preview-hls-iframe.ts */\n' + chunk.code;
          }
        }
      },
    },
  ],
};

// The demo intentionally consumes the *published* packages from jsDelivr
// (see the importmaps in demo/index.html and demo/advanced.html), so it
// reflects what consumers actually see. Every package listed below is
// marked external in both dev pre-bundle and build, which leaves the bare
// imports untouched in the served/built scripts; the browser then resolves
// them via the importmap. Local-only changes to src/ won't appear in the
// demo until they're published — for in-progress component work, use the
// unit / e2e tests, not the demo.
//
// `hls.js` is matched as both bare ("hls.js") and subpath ("hls.js/dist/...")
// because hls-video-element imports `hls.js/dist/hls.mjs` and advanced.js
// imports `hls.js` directly.
const externalPackages = [
  'media-preview-hls-iframe',
  'media-chrome',
  'hls-video-element',
  'custom-media-element',
  'media-tracks',
];
const isExternal = (id) =>
  externalPackages.includes(id) ||
  externalPackages.some((p) => id.startsWith(p + '/')) ||
  id === 'hls.js' ||
  id.startsWith('hls.js/');

const demoConfig = {
  root: resolve(__dirname, 'demo'),
  base: process.env.VITE_BASE || '/',
  optimizeDeps: {
    exclude: [...externalPackages, 'hls.js'],
  },
  server: { port: 5173 },
  build: {
    outDir: resolve(__dirname, 'dist-demo'),
    emptyOutDir: true,
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'demo/index.html'),
        advanced: resolve(__dirname, 'demo/advanced.html'),
        'vanilla-hlsjs': resolve(__dirname, 'demo/vanilla-hlsjs.html'),
      },
      external: isExternal,
    },
  },
};

export default defineConfig(({ mode }) =>
  mode === 'library' ? libraryConfig : demoConfig,
);
